-- AlterTable
ALTER TABLE `EventItem`
    ADD COLUMN `eventType` ENUM('REGULAR', 'SPECIAL') NOT NULL DEFAULT 'REGULAR',
    ADD COLUMN `scheduleType` ENUM('ONE_TIME', 'SATURDAY_SERVICE', 'WEDNESDAY_SERVICE', 'MONTHLY_15TH', 'FIRST_WEEKEND_LORDS_SUPPER', 'SECOND_WEEKEND_BIBLE_STUDY', 'FOURTH_WEEKEND_LEADERS_MEETING', 'LAST_SUNDAY_PRAYER_TEAM_VISIT', 'OTHER') NULL,
    ADD COLUMN `scheduleNotes` TEXT NULL,
    ADD COLUMN `locations` JSON NULL,
    ADD COLUMN `conductedBy` JSON NULL,
    ADD COLUMN `speakers` JSON NULL;
